brand:
  name: Voilà DT

menu-string: Menú

nav:
  - title: Servicios
    url: '#services'
  - title: Portafolio
    url: '#portfolio'
  - title: Nosotros
    url: '#about'
  - title: 'Equipo'
    url: '#team'
  - title: Contacto
    url: '#contact'

copyright: 'Voilà D. T. &copy; 2018 - 2019'

#quicklinks:
#  - title: 
#    url: ''

social-buttons:
  - icon: fa fa-twitter
    url: https://twitter.com/voiladt

